import React, { useState, useEffect } from 'react';
import Select from 'react-select';
import { db } from '../firebase';
import { collection, getDocs, doc, getDoc, setDoc } from 'firebase/firestore';

import { 
  TIME_SLOTS, 
  GENERATOR_DAYS, 
  DAY_LABELS, 
  ALL_PERIODS, 
  isLabSubject, 
  isEditedRoutine, 
  getDesignationLimit 
} from './routineUtils';

import { generateRoutine, formatFailureMessage } from './routineAlgorithm';
import './RoutineGenerator.css';

function RoutineGenerator() {
  // Stores all active routines loaded from firebase
  const [allRoutines, setAllRoutines] = useState([]);
  // Stores all available subjects loaded from firebase
  const [allSubjects, setAllSubjects] = useState([]);
  // Caches teachers list by subject id to prevent duplicate network calls
  const [teachersCache, setTeachersCache] = useState({});
  // Holds configuration states for each setup row visible in UI
  const [routineRows, setRoutineRows] = useState([]);
  // Tracks loading state when the algorithm is processing schedules
  const [loading, setLoading] = useState(false);
  // Holds global validation error strings
  const [error, setError] = useState('');
  // Stores calculation output grids generated by algorithm
  const [previews, setPreviews] = useState([]);
  // Tracks database update transactions status
  const [saving, setSaving] = useState(false);

  // Runs once on mount to populate routines and subjects choices
  useEffect(() => {
    const load = async () => {
      try {
        const [rSnap, sSnap] = await Promise.all([
          getDocs(collection(db, 'routines')),
          getDocs(collection(db, 'subjects'))
        ]);
        // Formats routines data for select drop down menus
        setAllRoutines(rSnap.docs.map(d => ({ id: d.id, ...d.data() })));
        // Formats subjects data for selection lists
        setAllSubjects(sSnap.docs.map(d => ({ id: d.id, name: d.data().name || d.id })));
      } catch { setError('Failed to load data.'); }
    };
    load();
  }, []);

  // Converts saved routines into value/label options for dropdown selection
  const routineOptions = allRoutines.map(r => ({ value: r.id, label: r.name || r.id }));

  // Pulls list of assigned instructors for a specific course topic
  const loadTeachersForSubject = async (subjectId) => {
    // Returns cached local data if this query ran previously
    if (teachersCache[subjectId]) return teachersCache[subjectId];
    const snap = await getDocs(collection(db, 'subjects', subjectId, 'teachers'));
    const teachers = {};
    snap.forEach(d => { teachers[d.id] = d.data().name || d.id; });
    // Saves findings to memory state
    setTeachersCache(prev => ({ ...prev, [subjectId]: teachers }));
    return teachers;
  };

  // Appends a new blank customization row section to UI layout list
  const addRoutineRow = () => {
    setRoutineRows(prev => [...prev, {
      id: Date.now(),
      selectedRoutine: null,
      subjects: [],
      activeChip: null,
      subjectPickerOpen: false
    }]);
  };

  // Discards an individual configuration row block using its identification token
  const removeRoutineRow = (rowId) => {
    setRoutineRows(prev => prev.filter(r => r.id !== rowId));
  };

  // Applies selective data state updates to properties of a target row item
  const updateRoutineRow = (rowId, changes) => {
    setRoutineRows(prev => prev.map(r => r.id === rowId ? { ...r, ...changes } : r));
  };

  // Links an option choice topic chip to an individual workspace row block
  const handleAddSubject = async (rowId, option) => {
    if (!option) return;
    // Requests matching instructors list from storage snapshot caches
    const teachers = await loadTeachersForSubject(option.value);
    const teacherOpts = Object.entries(teachers).map(([id, name]) => ({ value: id, label: name }));
    // Evaluates string parameters to discover structural course type definitions
    const isLab = isLabSubject(option.label);
    const newSubject = {
      id: Date.now(),
      subjectId: option.value,
      subjectName: option.label,
      isLab,
      // Sets initial class counts baseline based on course variant type
      theoryPerWeek: isLab ? 0 : 2,
      teacherOptions: teacherOpts,
      preferredTeacher: null
    };
    // Directs values update back into core rows array definitions
    setRoutineRows(prev => prev.map(r => r.id === rowId ? {
      ...r,
      subjects: [...r.subjects, newSubject],
      activeChip: newSubject.id,
      subjectPickerOpen: false
    } : r));
  };

  // Drops a curriculum item token block out from active row memory tracks
  const handleRemoveSubject = (rowId, subjectId) => {
    setRoutineRows(prev => prev.map(r => {
      if (r.id !== rowId) return r;
      return {
        ...r,
        subjects: r.subjects.filter(s => s.id !== subjectId),
        // Deselects item panel context tracker if target matches currently open item
        activeChip: r.activeChip === subjectId ? null : r.activeChip
      };
    }));
  };

  // Rewrites parameters within chosen curriculum objects (like lecture count values)
  const updateSubject = (rowId, subjectId, changes) => {
    setRoutineRows(prev => prev.map(r => {
      if (r.id !== rowId) return r;
      return { ...r, subjects: r.subjects.map(s => s.id === subjectId ? { ...s, ...changes } : s) };
    }));
  };

  // Evaluates UI input validity to confirm setup tracks can proceed safely
  const validate = () => {
    if (routineRows.length === 0) return 'Add at least one routine.';
    for (const row of routineRows) {
      if (!row.selectedRoutine) return 'Select a routine for each row.';
      if (row.subjects.length === 0) return `Add at least one subject to ${row.selectedRoutine.label}.`;
      for (const sub of row.subjects) {
        if (sub.teacherOptions.length === 0) return `No teachers found for ${sub.subjectName}.`;
      }
    }
    return null;
  };

  // Drives schedule arrangement calculation logic pipelines
  const handleGenerate = async () => {
    const err = validate();
    if (err) { setError(err); return; }
    setError('');
    setPreviews([]);
    setLoading(true);

    try {
      // Isolates unique instructor keys appearing across all row slots configurations
      const allTeacherIds = new Set();
      routineRows.forEach(row => {
        row.subjects.forEach(sub => {
          sub.teacherOptions.forEach(t => allTeacherIds.add(t.value));
        });
      });

      // Synchronizes data files maps detailing existing classes for selected teachers
      const facultyMap = {};
      await Promise.all([...allTeacherIds].map(async (id) => {
        try {
          const [parentSnap, slotsSnap] = await Promise.all([
            getDoc(doc(db, 'Faculty_Routine', id)),
            getDocs(collection(db, 'Faculty_Routine', id, 'slots'))
          ]);
          const parentData = parentSnap.exists() ? parentSnap.data() : {};
          const slots = {};
          slotsSnap.forEach(d => { slots[d.id] = d.data(); });
          facultyMap[id] = { ...parentData, slots };
        } catch {
          facultyMap[id] = { slots: {} };
        }
      }));

      const loadUsed = {};
      const results = [];

      // Computes calendar timeline coordinate positions loop by loop
      for (const row of routineRows) {
        const existingSlots = {};
        // Loads hardlocked items already set inside the target class timeline paths
        for (const day of GENERATOR_DAYS) {
          const snap = await getDocs(collection(db, 'routines', row.selectedRoutine.value, day));
          existingSlots[day] = {};
          snap.forEach(d => { existingSlots[day][parseInt(d.id)] = d.data(); });
        }

        // Activates the external mathematical core algorithm calculator script module
        const { grid, failures } = generateRoutine(row.subjects, existingSlots, facultyMap, loadUsed);
        const formattedFailures = failures.map(formatFailureMessage);
        
        results.push({
          routineId: row.selectedRoutine.value,
          routineName: row.selectedRoutine.label,
          grid,
          failures: formattedFailures,
          isEdited: isEditedRoutine(existingSlots)
        });
      }

      setPreviews(results);
    } catch (err) {
      setError('Failed: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  // Handles bulk transaction disk write routing paths down to firestore database paths
  const handleSaveAll = async () => {
    if (previews.length === 0) return;
    setSaving(true);
    setError('');

    try {
      for (const preview of previews) {
        for (const day of GENERATOR_DAYS) {
          for (const period of ALL_PERIODS) {
            const cell = preview.grid[day]?.[period];
            // Discards processing updates if spot is clear or already contains locked legacy inputs
            if (!cell?.occupied || cell.existing) continue;
            
            const dayKey = day;
            const slotId = `${dayKey}_${period}`;
            const routineDocRef = doc(db, 'routines', preview.routineId, dayKey, String(period));
            
            // Reads targets to catch if a legacy instructor is being replaced by updates
            const existingRoutineSnap = await getDocs(collection(db, 'routines', preview.routineId, dayKey));
            const existingSlotData = existingRoutineSnap.docs.find(d => d.id === String(period));
            let previousTeacherId = null;
            let previousLoad = 0;
            
            if (existingSlotData?.exists()) {
              const data = existingSlotData.data();
              if (data.tid && data.tid !== cell.teacherId) {
                previousTeacherId = data.tid;
                previousLoad = data.load || (data.isLab ? 1.0 : 1.5);
              }
            }
            
            // Commits calculated class parameters block context to standard routine paths
            await setDoc(routineDocRef, {
              sname: cell.subjectName,
              scode: cell.subjectCode,
              tname: cell.teacherName,
              tid: cell.teacherId,
              isLab: cell.isLab,
              load: cell.load
            }, { merge: true });
            
            // Replicates properties data over into tracking files inside faculty profiles tracks
            await setDoc(
              doc(db, 'Faculty_Routine', cell.teacherId, 'slots', slotId),
              {
                routineId: preview.routineId,
                routineName: preview.routineName,
                subjectName: cell.subjectName,
                subjectCode: cell.subjectCode,
                isLab: cell.isLab,
                period: period,
                day: dayKey,
                load: cell.load
              },
              { merge: true }
            );
            
            // Updates operational load capacity balances inside instructor parent files
            const teacherRef = doc(db, 'Faculty_Routine', cell.teacherId);
            const teacherSnap = await getDoc(teacherRef);
            
            if (teacherSnap.exists()) {
              const teacherData = teacherSnap.data();
              const limit = getDesignationLimit(cell.teacherName);
              const currentRemaining = teacherData.remainingLoad ?? limit;
              
              const existingSlotSnap = await getDoc(doc(db, 'Faculty_Routine', cell.teacherId, 'slots', slotId));
              const isNewSlot = !existingSlotSnap.exists() || !existingSlotSnap.data().routineId;
              
              // Only subtracts workload weight balance points if coordinate slot is completely fresh
              if (isNewSlot) {
                const newRemaining = Math.max(0, currentRemaining - cell.load);
                await setDoc(teacherRef, {
                  teacherName: cell.teacherName,
                  maxLoad: limit,
                  remainingLoad: Number(newRemaining.toFixed(2))
                }, { merge: true });
              }
            } else {
              // Initializes a pristine status document layer if teacher was unregistered previously
              await setDoc(teacherRef, {
                teacherName: cell.teacherName,
                maxLoad: getDesignationLimit(cell.teacherName),
                remainingLoad: Number((getDesignationLimit(cell.teacherName) - cell.load).toFixed(2))
              }, { merge: true });
            }
            
            // Returns work balance capabilities credit score back to previous displaced instructors
            if (previousTeacherId) {
              const prevTeacherRef = doc(db, 'Faculty_Routine', previousTeacherId);
              const prevTeacherSnap = await getDoc(prevTeacherRef);
              
              if (prevTeacherSnap.exists()) {
                const prevData = prevTeacherSnap.data();
                const prevLimit = getDesignationLimit(cell.teacherName);
                const prevCurrentRemaining = prevData.remainingLoad ?? prevLimit;
                const restoredRemaining = Math.min(prevLimit, prevCurrentRemaining + previousLoad);
                
                await setDoc(prevTeacherRef, {
                  teacherName: prevData.teacherName,
                  maxLoad: prevLimit,
                  remainingLoad: Number(restoredRemaining.toFixed(2))
                }, { merge: true });
              }
            }
          }
        }
      }
      
      alert('✅ All routines saved successfully!');
      setPreviews([]);
    } catch (err) {
      setError('❌ Save failed: ' + err.message);
      console.error('Save error:', err);
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="rg-page">
      <h2 className="rg-title">Routine Generator</h2>
      <p className="rg-subtitle">Add routines, configure subjects, then generate all at once.</p>

      {/* Renders data input form modules sequentially row by row */}
      {routineRows.map((row, rowIdx) => {
        const usedSubjectIds = row.subjects.map(s => s.subjectId);
        const availableSubjects = allSubjects
          .filter(s => !usedSubjectIds.includes(s.id))
          .map(s => ({ value: s.id, label: `[${s.id}] ${s.name}` }));

        const activeSubject = row.subjects.find(s => s.id === row.activeChip);

        return (
          <div key={row.id} className="rg-routine-card">
            <div className="rg-routine-header">
              <span className="rg-routine-title">Routine {rowIdx + 1}</span>
              <button className="rg-remove-btn" onClick={() => removeRoutineRow(row.id)}>✕ Remove</button>
            </div>

            <div className="rg-field">
              <label className="rg-label">Select Class Routine</label>
              <Select
                options={routineOptions.filter(opt =>
                  !routineRows.find(r => r.id !== row.id && r.selectedRoutine?.value === opt.value)
                )}
                value={row.selectedRoutine}
                onChange={(opt) => updateRoutineRow(row.id, { selectedRoutine: opt })}
                placeholder="Choose routine..."
                isClearable
              />
            </div>

            <div className="rg-field">
              <label className="rg-label">Subjects</label>
              <div className="rg-chip-bar">
                {row.subjects.map(sub => (
                  <div key={sub.id}
                    className={`rg-chip ${sub.isLab ? 'lab' : 'theory'} ${row.activeChip === sub.id ? 'active' : ''}`}
                    onClick={() => updateRoutineRow(row.id, {
                      activeChip: row.activeChip === sub.id ? null : sub.id,
                      subjectPickerOpen: false
                    })}>
                    {sub.subjectName.replace(/^\[.*?\]\s*/, '')}
                    {sub.isLab && <span className="rg-lab-badge">LAB</span>}
                    <button className="rg-chip-x"
                      onClick={(e) => { e.stopPropagation(); handleRemoveSubject(row.id, sub.id); }}>✕</button>
                  </div>
                ))}

                {/* Alternates between a basic activation button or active auto-focused choice fields list */}
                {!row.subjectPickerOpen ? (
                  <button className="rg-add-chip"
                    onClick={() => updateRoutineRow(row.id, { subjectPickerOpen: true, activeChip: null })}>
                    + Add Subject
                  </button>
                ) : (
                  <div className="rg-subject-picker-wrapper">
                    <Select autoFocus options={availableSubjects}
                      onChange={(opt) => handleAddSubject(row.id, opt)}
                      placeholder="Search subject..." menuIsOpen
                      onBlur={() => updateRoutineRow(row.id, { subjectPickerOpen: false })} />
                  </div>
                )}
              </div>

              {/* Individual Topic Parameter Parameter Setup Drawer Interface Block */}
              {activeSubject && (
                <div className="rg-panel">
                  <div className="rg-panel-title">
                    {activeSubject.subjectName.replace(/^\[.*?\]\s*/, '')}
                    {activeSubject.isLab && <span className="rg-lab-badge">LAB</span>}
                  </div>

                  {activeSubject.isLab ? (
                    <p className="rg-panel-lab-note">
                      Lab = 3 consecutive periods. Teacher auto-selected from available list.
                    </p>
                  ) : (
                    <div className="rg-inline-row rg-field">
                      <label className="rg-inline-label">Classes/week:</label>
                      <input type="number" min={1} max={8} value={activeSubject.theoryPerWeek}
                        className="rg-num-input"
                        onChange={e => updateSubject(row.id, activeSubject.id, {
                          theoryPerWeek: parseInt(e.target.value) || 1
                        })} />
                    </div>
                  )}

                  <div className="rg-field" style={{ marginTop: '12px' }}>
                    <label className="rg-inline-label">Preferred Teacher (optional):</label>
                    <Select
                      options={[{ value: null, label: 'No preference' }, ...activeSubject.teacherOptions]}
                      value={activeSubject.preferredTeacher || { value: null, label: 'No preference' }}
                      onChange={(opt) => updateSubject(row.id, activeSubject.id, {
                        preferredTeacher: opt?.value ? opt : null
                      })}
                      placeholder="No preference..."
                    />
                  </div>
                  <div className="rg-panel-teacher-info">
                    {activeSubject.teacherOptions.length} teacher(s) available as fallback.
                  </div>
                </div>
              )}
            </div>
          </div>
        );
      })}

      <button className="rg-add-routine-btn" onClick={addRoutineRow}>+ Add Routine</button>

      {error && <div className="rg-error">{error}</div>}

      <button className="rg-generate-btn" onClick={handleGenerate} disabled={loading}>
        {loading ? 'Generating...' : 'Generate All Routines →'}
      </button>

      {/* Outputs structural visual grid matrix blocks matching generated results arrays maps */}
      {previews.length > 0 && (
        <>
          <button className="rg-save-btn" onClick={handleSaveAll} disabled={saving}>
            {saving ? '💾 Saving...' : '💾 Save All Routines'}
          </button>

          <div className="rg-preview-section">
            <h3 className="rg-preview-title">Preview</h3>
            {previews.map((preview) => (
              <div key={preview.routineId} className="rg-preview-routine">
                <div className="rg-preview-routine-name">
                  {preview.routineName}
                  {preview.isEdited && <span className="rg-edited-badge"> EDITED</span>}
                </div>

                {/* Outputs warning metrics errors lines summary logs if processing items hit dead ends */}
                {preview.failures.length > 0 && (
                  <div className="rg-failures-container">
                    {preview.failures.map((f, i) => (
                      <div key={i} className="rg-fail">{f}</div>
                    ))}
                  </div>
                )}

                {/* Core Calendar Visual Grid Data Table Structure */}
                <div className="rg-table-wrapper">
                  <table className="rg-table">
                    <thead>
                      <tr>
                        <th>Day / Time</th>
                        {TIME_SLOTS.map((slot, i) => (
                          <th key={i} className={slot.isLunch ? 'lunch' : ''}>{slot.time}</th>
                        ))}
                      </tr>
                    </thead>
                    <tbody>
                      {GENERATOR_DAYS.map(day => (
                        <tr key={day}>
                          <td className="day-col">{DAY_LABELS[day]}</td>
                          {TIME_SLOTS.map((slot, i) => {
                            if (slot.isLunch) return <td key={i} className="lunch-col">Lunch</td>;
                            const cell = preview.grid[day]?.[slot.period];
                            if (!cell?.occupied) return <td key={i} className="empty-col">—</td>;
                            if (cell.existing) return (
                              <td key={i} className="existing-col">
                                <div className="rg-cell-subject existing">{cell.data?.sname || 'Existing'}</div>
                                <div className="rg-cell-teacher">{cell.data?.tname || ''}</div>
                              </td>
                            );
                            return (
                              <td key={i} className={cell.isLab ? 'lab-col' : 'theory-col'}>
                                <div className={`rg-cell-subject ${cell.isLab ? 'lab' : 'theory'}`}>
                                  {cell.subjectName}
                                </div>
                                <div className="rg-cell-teacher">{cell.teacherName}</div>
                                {cell.isLab && <div className="rg-cell-lab-tag">LAB</div>}
                              </td>
                            );
                          })}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                <p className="rg-preview-legend">Bl Theory &nbsp; Vi Lab &nbsp; Gr Existing</p>
              </div>
            ))}
          </div>
        </>
      )}
    </div>
  );
}

export default RoutineGenerator;